Added details about subscription error in console log (#13)
For example, when I faced with #12, I just saw `error` in console, which is not helpful at all. After debugging I saw that real error was:

> DOMException: Registration failed - gcm_sender_id not found in manifest

We need to add such details to error so it will be more informative.